### ISSUE TITLE
[Bug] Incorrect Ranks Displayed

### ISSUE THREAD

**Issue by danielmillar** [tanishqmanuja/valo-kit#1]
## Problem

A bug has been identified in the application that causes the incorrect display of ranks for both the Rank and Peak Rank columns. This issue was first encountered after a Swiftplay game and has remained even after restarting both vRY and Valorant.

## Steps to Reproduce

Unfortunately, a reproducible pattern for this issue could not be established as it appears to have materialized spontaneously.

## Expected Outcome

The expected outcome was for the Rank column to display "Ascendant 1" and the Peak Rank column to display "Ascendant 1 (E6A1)".

## Actual Outcome

The actual outcome was that the Rank column displayed "Immortal 1" and the Peak Rank column displayed "Immortal 1 (E6A1)". 

## Additional Information

The bug is being encountered using the latest version of vRY, version 0.5.1.

**Comment by tanishqmanuja** [comment]
Can you provide any logs or screenshots for debugging?

**Comment by danielmillar** [comment]
I've attached the log file from when I first noticed the issue: [cli-2023-02-10-15.log](https://github.com/tanishqmanuja/valo-kit/files/10714059/cli-2023-02-10-15.log)
Then this is the log file from today's usage with my most recent game for extra logging: [cli-2023-02-11-16.log](https://github.com/tanishqmanuja/valo-kit/files/10714061/cli-2023-02-11-16.log)

I don't have any before screenshots of vRY and cause the bug is persistent, I have only have screenshot of my most recent game where it shows the incorrect ranks and also attached is the end game scoreboard for what the ranks should be. ![ActualResult](https://user-images.githubusercontent.com/48495731/218268880-111530fb-d2d3-41d1-a54b-755c53250aa0.png)

![Scoreboard](https://user-images.githubusercontent.com/48495731/218269295-779109ea-1488-45d9-8b49-4ceaef37564f.png)

**Comment by tanishqmanuja** [comment]
Thanks for the log, Looking at it maybe the rank tier number to rank name conversion is bugged. Will get fixed soon.
Btw can you try deleting the cache folder and report if it changes anything?

**Comment by danielmillar** [comment]
Apologies I should have mentioned that I did already try to delete the cache folder but the problem still persists. Hope this helps!

**Comment by tanishqmanuja** [comment]
If cache didnt help then code is bugged for sure because no api error in logs. My peak is Platinum 2 that's why i wasn't able to find this bug sooner. This only happens for changed ranked system as the rank number which previously pointed to immortal now represents ascendant.

**Comment by tanishqmanuja** [comment]
Can you check with latest release v0.6.1, also delete cache after copying the exe file.

**Comment by danielmillar** [comment]
Sorry for the late response but this new release does indeed resolve the issue, thanks for being so prompt about it!
